### VECTORS

## ADDING AND DELETING VECTOR ELEMENTS
# YOU CANNOT DELETE OR ADD ELEMENTS TO VECTORS
# UNLESS YOU ASSIGN A NEW VARIABLE.
x <- c(88, 5, 12, 13)
x <- c(x[1:3], 168, x[4]) #SUBSETTING AND ADDING ELEMENTS
# Obtaining length
length(x)


## INDEXING VECTORS
# USE NEGATIVE INDEX IN VECTORS TO EXCLUDE ELEMENT ELEMENT 
# AT THAT INDEX FROM THE NEW VECTOR
y <- c(88, 5, 12, 13)
y <- y[-1] #REMOVES FIRST ELEMENT FROM VECTOR
print(y)
y <- y[-length(y)] #REMOVES LAST ELEMENT FROM RESULTING VECTOR
print(y)


## REPEATINB VECTORS USING rep()
# rep(x, times)
new <- c(5,12,13)
rep(new,3)
# USE rep(x, each=) TO TO REPEAT EACH ELEMENT NUMBER OF TIMES 
# BEFORE THE NEXT

rep(new, each=4)


## USE all() or any() functions
# ANY REPORTS WHETHER ANY OF THOSE VALUES IS TRUE
# ALL FUNCTIONS WORKS SIMILARLY BUT REPORTS OF ALL 
# VALUES ARE TRUE

x <- 1:10
any(x > 8) # TRUE
any(x > 88) # FALSE
all(x > 88) # FALSE
all(x > 0) # TRUE
